### PR TITLE
group tabs by window

### PR DESCRIPTION
**Pull request by nohzafk**
currently Group Existing Tabs will group all tabs from all windows to current window, which is not desired as many windows are used.

this change make group existign tabs only group tabs of current window.

maybe should add an option for this feature.

### CODE REVIEW

**Comment by nohzafk** [comment]
need more test for this change

**Review by MichaelYuhe — APPROVED** [review]
LGTM

**Comment by nohzafk** [comment]
With this modification, think that it now function correctly.

**Review by MichaelYuhe — APPROVED** [review]
LGTM

**Pull request merged**
